- name: oc_delete_deployment
  hosts: all
  tasks:
  environment:
    KUBECONFIG: "/home/adminlocal/kubeconfig-orin"
  tasks:
  - name: Delete deployment
    shell: oc delete -f deployment.yaml --insecure-skip-tls-verify=true
      chdir: /home/adminlocal/orin
    register: command_output

  - debug:
      msg: "{{ command_output }}"