- name: Login
  hosts: localhost
  gather_facts: false
  environment:
    KUBECONFIG: "/home/adminlocal/kubeconfig-orin"
  tasks:
  - name: Create a namespace with token  
    shell: oc get all --insecure-skip-tls-verify=true