- name: oc_get_all
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Create a namespace with token  
    shell: KUBECONFIG=/home/adminlocal/kubeconfig-orin oc get all --insecure-skip-tls-verify=true
    #shell: KUBECONFIG: "/home/adminlocal/kubeconfig-orin" oc get all --insecure-skip-tls-verify=true