- name: oc_get_all
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Create a namespace with token  
    shell: whoami && pwd && ls -la /home/adminlocal/kubeconfig-orin
    register: command_output

  - debug:
    var: command_output.stdout_lines
    
    #shell: KUBECONFIG: "/home/adminlocal/kubeconfig-orin" oc get all --insecure-skip-tls-verify=true