- name: oc_get_all
  hosts: all
  tasks:
  - name: Create a namespace with token  
    shell: whoami && pwd && id && hostname
    register: command_output

  - debug:
      msg: "{{ command_output }}"